Feature/market attribute
drew2323/v2trading pull request #185
Opened 2024-04-02 14:36 UTC by pvlasak

Ahoj, sdilim prvni verzi upravy tykajici se atributu market v run manager record. Zitra v meetingu muzeme probrat.

2024-04-04 10:51 UTC, drew2323 commented on v2realbot/common/model.py
> +    market: Optional[Market] = None
def. value US

2024-04-04 10:54 UTC, drew2323 commented on v2realbot/common/transform.py
> +        market=str(row['market']) if row['market'] is not None else None,
nemusi byt str()

2024-04-04 10:55 UTC, drew2323 commented on v2realbot/controller/run_manager.py
> +            int(new_record.ilog_save), 'US',
new_record.market

2024-04-04 10:56 UTC, drew2323 commented on v2realbot/controller/run_manager.py
> +                value = 'US'
value = str(value)

2024-04-04 11:01 UTC, drew2323 commented on v2realbot/controller/run_manager.py
> +def fetch_all_markets_in_run_manager() -> list:
asi pryč

2024-04-04 11:13 UTC, drew2323 commented on v2realbot/scheduler/ap_scheduler.py
> +            market_value = record.market.value if record.market else None
do jobu jako argument pauze record.id , market se pak dotahne dle id v _start_runman_record

2024-04-04 11:14 UTC, drew2323 commented on v2realbot/scheduler/ap_scheduler.py
> +def start_runman_record(id: UUID, market, debug_date = None):
market pryc

2024-04-04 11:14 UTC, drew2323 commented on v2realbot/scheduler/ap_scheduler.py
>      res, record, msg = _start_runman_record(id=id, market=market, debug_date=debug_date)
market pryc

2024-04-04 11:14 UTC, drew2323 commented on v2realbot/scheduler/ap_scheduler.py
> +def stop_runman_record(id: UUID, market, debug_date = None):
market pryc

2024-04-04 11:14 UTC, drew2323 commented on v2realbot/scheduler/ap_scheduler.py
>      res, record, msg = _stop_runman_record(id=id, market=market, debug_date=debug_date)
market pryc

2024-04-04 11:15 UTC, drew2323 commented on v2realbot/scheduler/ap_scheduler.py
> +    if market == "US" or market is None:
record.market

2024-04-04 11:20 UTC, drew2323 commented on v2realbot/scheduler/ap_scheduler.py
> +        elif res == 1:
market None rusime, typ marketu bude vzdy dany enumeraci s danym defaultem

2024-04-04 11:28 UTC, drew2323 commented on v2realbot/scheduler/scheduler.py
> +        elif market is None:
market None rusime, vytvarime vidlicku pro CRYPTO, ktera bude vracet nowNY, a open cas a close cas

2024-04-04 11:29 UTC, drew2323 requested changes
see comments

2024-04-10 10:12 UTC, drew2323 commented on v2realbot/common/model.py
> +    market: Optional[Market] = 'US'
Market.US

2024-04-10 10:16 UTC, drew2323 commented on v2realbot/controller/run_manager.py
>              elif key == "market":
zkusit pryc celou sekci

2024-04-10 10:19 UTC, drew2323 commented on v2realbot/scheduler/ap_scheduler.py
>              market_value = record.market.value if record.market else None
pryc

2024-04-10 10:30 UTC, drew2323 commented on v2realbot/scheduler/scheduler.py
> +        if market == "US" or market == "CRYPTO":
1) pouzit Market.US a Market.CRYPTO
2) pro market US nechat jak je (tzn. dotahnout z is_market_day fce)
3) vytvorit vetev Market.CRYPTO - která vrátí
- now_market_datetime - nowNY(dle variable CRYPTO_TIMEZONE = zoneNY) datetime.now().astimezone(zoneNY)
- market_open_datetime - začátek now_market_datetime (datum + 0:00:00)
- matket_close_datetime - konec now_market_datetime  (datum + 23:59:59)

2024-04-17 09:46 UTC, pvlasak commented
Instructions:
---------------------
1. connect to SQLite DB and add a column named market to run_manager table: 

import sqlite3
from v2realbot.common.db import sqlite_db_file

conn = sqlite3.connect(sqlite_db_file)
cursor = conn.cursor()
cursor.execute("""ALTER TABLE run_manager ADD COLUMN market TEXT;""")
cursor.execute("""UPDATE run_manager SET market='US';""")
conn.commit()
conn.close()

3. Use application as usual. Any new run manager record is set by default for US stock market
4. You can also use sequence of SQL commands in `v2trading_create_db.sql` to create a new SQLite database from scratch

2024-04-17 10:10 UTC, drew2323 approved these changes

2024-04-17 10:14 UTC, merged